#!/usr/bin/env bash
#script that gives information on the server

web ()
{
	result=$(dig "$2.$1" | grep -A1 "ANSWER SECTION:" | tail -1)
	echo "$2 $result" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}' 
}

if [ "$#" -eq 1 ]
then
	web "$1" "www"
	web "$1" "lb-01"
	web "$1" "web-01"
	web "$1" "web-02"
elif [ "$#" -eq 2 ]
then
	web "$1" "$2"
fi
