#!/usr/bin/env bash
#Configure Nginx server so that /redirect_me is redirecting to another page

#Install nginx
sudo apt-get update
sudo apt-get install -y nginx


#add the following configuration to the existing server block
string_to_replace="server_name _;\n\nlocation\/redirect_me {\n\treturn 301 https:\/\/www.google.com;\n}"
sudo sed -i s/"server_name _;"/"$string_to_replace"/g /etc/nginx/sites-enabled/default

#Restart Nginx
service nginx restart
