#!/usr/bin/env bash
#Config files for server lb-01

sudo apt-get update -y
sudo apt-get install -y haproxy

echo "
frontend Shogo_fr
	bind *:80
	default_backend Shogo_bk

backend Shogo_bk
	balance roundrobin
	server 144956-web-01 100.25.220.195:80 check
	server 144956-web-02 52.91.168.113:80 check
 " >> /etc/haproxy/haproxy.cfg

sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
