#!/usr/bin/env bash
#A script that configures an ubuntu server
#resolves localhost to 127.0.0.2
#resolves facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -e' s/127.0.0.1	localhost/127.0.0.2	localhost/g' /etc/hosts > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
